name: Update Table

on: [push]

jobs:
  validate_test:
    name: validate
    uses: ./.github/workflows/ocaml.yml
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: pip install -r requirements.txt 
        
      - name: Install grewpy_backend
        run: pip3 install grewpy --upgrade

      - name: Update table
        run: python tools/update_tables.py  
        
