name: Update Table

on:
  push:
    branches:
      - main  # Remplacez par la branche appropriée

jobs:
  update:
    runs-on: ubuntu-latest
   
   steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.6
      
      - name: Install grewpy_backend
        run: pip3 install grewpy --upgrade

      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Update table
        run: python tools/update_tables.py  
